# Generated by Django 5.1.4 on 2026-10-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categoria_slug_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tiendanube_category_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID externo de Tiendanube', null=True, unique=True),
        ),
    ]
