# Generated by Django 5.1.4 on 2026-10-08 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=200)),
                ('elemento', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(default='Administrador', max_length=150)),
                ('tipo_accion', models.CharField(choices=[('producto', 'Producto'), ('categoria', 'Categoría'), ('oferta', 'Oferta'), ('pedido', 'Pedido'), ('usuario', 'Usuario'), ('general', 'General')], default='general', max_length=50)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'actividades',
                'ordering': ['-fecha'],
            },
        ),
    ]
