# Generated by Django 6.0.7 on 2026-09-23
# Migration para agregar campo producto_simple al modelo Producto
# SIN backfill automático - se clasificará manualmente después de inspección

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_producto_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_simple',
            field=models.BooleanField(
                default=False,
                db_index=True,
                help_text='True si es producto simple (sin variantes visibles), False si tiene variantes'
            ),
        ),
    ]
