# Generated by Django 5.1.4 on 2026-10-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_normalizar_productos_simples'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiendanube_product_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID externo de Tiendanube', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='variante',
            name='atributos_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Atributos de Tiendanube no mapeados a Color/Talla/Diseño'),
        ),
        migrations.AddField(
            model_name='variante',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio real de esta variante (Tiendanube)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variante',
            name='stock_infinito',
            field=models.BooleanField(default=False, help_text='True si el inventario no se gestiona'),
        ),
        migrations.AddField(
            model_name='variante',
            name='tiendanube_variant_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID externo de Tiendanube', null=True, unique=True),
        ),
    ]
