# Generated by Django 5.1.4 on 2026-10-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_producto_tiendanube_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], db_index=True, default='imagen', max_length=10),
        ),
    ]
